#!/bin/bash
a=23
echo $a
b=$a
echo $b
a='echo Hello!'
echo $a
#注意，如果直接在命令扩展结构中使用一个!，在命令行中将不能工作。
#但是，在脚本里边使用的话，历史功能是被关闭的，所以就能够正常运行。

#把ls -l的结果给a
a=$(ls -l)

#这样引用，ls的结果中的所有空白部分都没了（包括换行）
echo $a
echo
echo "$a"

a=2335
#将23替换成BB
b=${a/23/BB}

exit 0
