#!/bin/bash
#Function:根据用户名查询该用户的所有信息
read -p "请输入要查询的用户名：" NAME
echo "----------------------------------"
n=`cat /etc/passwd | awk -F: '$1~/^'$NAME'$/{print}' | wc -l`
if [ $n -eq 0 ];then
        echo "该用户不存在！"
        echo "----------------------------------"
else
        echo "该用户的用户名：$NAME"
        echo "该用户的UID：`cat /etc/passwd |awk -F: '$1~/^'$NAME'$/{print}' | awk -F: '{print $3}'`"
        #echo "该用户的组为：`id $NAME | awk -F'[, ]' '{print $3}'`"
        echo "该用户的组为：`id $NAME | awk '{print $3}'`"
        echo "该用户的GID为：`cat /etc/passwd | awk -F: '$1~/^'$NAME'$/{print}' | awk -F: '{print $4}'`"
        echo "该用户的家目录为：`cat /etc/passwd | awk -F: '$1~/^'$NAME'$/{print}' | awk -F: '{print $6}'`"
        #赋值没有空格
        Login=`cat /etc/passwd | awk -F: '$1~/^'$NAME'$/{print}' | awk -F: '{print $7}'`
        #比较中间有空格
        if [ $Login == "/bin/bash" ];then
                echo "该用户有登录系统的权限！！"
                echo "----------------------------------"
        elif [ $Login == "/bin/false" ];then
                echo "该用户没有登录系统的权限！！"
                echo "----------------------------------"
        fi
fi
